name: .NET Build

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore VeterinaryClinic.Solution.sln

      - name: Build solution
        run: dotnet build VeterinaryClinic.Solution.sln --configuration Release --no-restore

      # - name: Run tests
      # run: dotnet test VeterinaryClinic.Solution.sln --no-build --verbosity normal

      - name: Publish API
        run: dotnet publish VeterinaryClinic.API/VeterinaryClinic.API.csproj --configuration Release --output ./publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: veterinaryclinic-api
          path: ./publish
